version: '3.8'

services:
  backend:
    container_name: rss-aggregator
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - DB_URL=${DB_URL}
    ports:
      - 8080:8080
    env_file:
      - .env
    develop:
      watch:
        - path: ./go.mod
          action: rebuild
        - path: ./sql
          action: rebuild
        - path: ./
          target: .
          action: sync
        